apiVersion: apps/v1
kind: Deployment
metadata:
 name: userinfo-app-rest-api
spec:
 replicas: 4
 selector:
  matchLabels:
   app: userinfo-rest
 template:
  metadata:
   labels:
    app: userinfo-rest
  spec:
   containers:
    - name: userinfo-rest-container
      image: 10052020/userinfo-image:8
      ports:
       - name: http
         containerPort: 80
         protocol: TCP
      env:
       - name: SERVER_NAME_ENV
         valueFrom:
          configMapKeyRef:
           name: db-config-map
           key: SERVER_NAME
       - name: DATABASE_NAME_ENV
         valueFrom:
          configMapKeyRef:
           name: db-config-map
           key: DATABASE_NAME
       - name: USER_NAME_ENV
         valueFrom:
          configMapKeyRef:
           name: db-config-map
           key: USER_NAME
       - name: DB_PASSWORD_ENV
         valueFrom:
          secretKeyRef:
           name: secret-userinfo
           key: DB_PASSWORD